In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def BayesianClassifier(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier = GaussianNB()
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [4]:
path_train = '../TrainTestData/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
BayesianClassifier(path_train,path_test)

[[6331 1827]
 [2204 3822]]
              precision    recall  f1-score   support

           0       0.78      0.74      0.76      8535
           1       0.63      0.68      0.65      5649

    accuracy                           0.72     14184
   macro avg       0.71      0.71      0.71     14184
weighted avg       0.72      0.72      0.72     14184



# Virginia

In [5]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
BayesianClassifier(path_train,path_test)

[[6648 1907]
 [1999 3630]]
              precision    recall  f1-score   support

           0       0.78      0.77      0.77      8647
           1       0.64      0.66      0.65      5537

    accuracy                           0.72     14184
   macro avg       0.71      0.71      0.71     14184
weighted avg       0.73      0.72      0.73     14184



# Hungary

In [6]:
path_train = '../traintestdata/hun_train.csv'
path_test = '../traintestdata/hun_test.csv'
BayesianClassifier(path_train,path_test)

[[6463 1927]
 [2078 3716]]
              precision    recall  f1-score   support

           0       0.77      0.76      0.76      8541
           1       0.64      0.66      0.65      5643

    accuracy                           0.72     14184
   macro avg       0.71      0.71      0.71     14184
weighted avg       0.72      0.72      0.72     14184



# Switzerland

In [7]:
path_train = '../traintestdata/swi_train.csv'
path_test = '../traintestdata/swi_test.csv'
BayesianClassifier(path_train,path_test)

[[6178 1802]
 [2312 3892]]
              precision    recall  f1-score   support

           0       0.77      0.73      0.75      8490
           1       0.63      0.68      0.65      5694

    accuracy                           0.71     14184
   macro avg       0.70      0.71      0.70     14184
weighted avg       0.72      0.71      0.71     14184



# European

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
BayesianClassifier(path_train,path_test)

[[52  8]
 [ 7 59]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.87        59
           1       0.89      0.88      0.89        67

    accuracy                           0.88       126
   macro avg       0.88      0.88      0.88       126
weighted avg       0.88      0.88      0.88       126



# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
BayesianClassifier(path_train,path_test)

[[ 98  23]
 [ 24 131]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81       122
           1       0.85      0.85      0.85       154

    accuracy                           0.83       276
   macro avg       0.83      0.83      0.83       276
weighted avg       0.83      0.83      0.83       276

