In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def RandomForest(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier = RandomForestClassifier(n_estimators=100, random_state=42)
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [3]:
path_train = '../TrainTestData/cle_train.csv'
path_test = '../TrainTestData/cle_test.csv'
RandomForest(path_train,path_test)

[[6825 2258]
 [1710 3391]]
              precision    recall  f1-score   support

           0       0.75      0.80      0.77      8535
           1       0.66      0.60      0.63      5649

    accuracy                           0.72     14184
   macro avg       0.71      0.70      0.70     14184
weighted avg       0.72      0.72      0.72     14184



# Virginia

In [4]:
path_train = '../TrainTestData/vir_train.csv'
path_test = '../TrainTestData/vir_test.csv'
RandomForest(path_train,path_test)

[[6938 2276]
 [1709 3261]]
              precision    recall  f1-score   support

           0       0.75      0.80      0.78      8647
           1       0.66      0.59      0.62      5537

    accuracy                           0.72     14184
   macro avg       0.70      0.70      0.70     14184
weighted avg       0.72      0.72      0.72     14184



# Hungary

In [5]:
path_train = '../TrainTestData/hun_train.csv'
path_test = '../TrainTestData/hun_test.csv'
RandomForest(path_train,path_test)

[[6838 2346]
 [1703 3297]]
              precision    recall  f1-score   support

           0       0.74      0.80      0.77      8541
           1       0.66      0.58      0.62      5643

    accuracy                           0.71     14184
   macro avg       0.70      0.69      0.70     14184
weighted avg       0.71      0.71      0.71     14184



# Switzerland

In [6]:
path_train = '../TrainTestData/swi_train.csv'
path_test = '../TrainTestData/swi_test.csv'
RandomForest(path_train,path_test)

[[6861 2350]
 [1629 3344]]
              precision    recall  f1-score   support

           0       0.74      0.81      0.78      8490
           1       0.67      0.59      0.63      5694

    accuracy                           0.72     14184
   macro avg       0.71      0.70      0.70     14184
weighted avg       0.72      0.72      0.72     14184



# Combined

In [8]:
path_train = '../TrainTestData/com_train.csv'
path_test = '../TrainTestData/com_test.csv'
RandomForest(path_train,path_test)

[[28003  9237]
 [ 6210 13286]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78     34213
           1       0.68      0.59      0.63     22523

    accuracy                           0.73     56736
   macro avg       0.72      0.70      0.71     56736
weighted avg       0.72      0.73      0.72     56736

