In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import preprocessing as sk_preprocessing

In [2]:
def svm_train():
    #load the train-test data
    Train = pd.read_csv('../TrainTestdata/com_train.csv')
    Test = pd.read_csv('../TrainTestdata/com_test.csv')
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarylize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)
    
    #SVM
    svc.fit(X_train, Y_train_binary.values.ravel())
    y_pred = svc.predict(X_test)
    print(confusion_matrix(Y_test_binary, y_pred))
    print(classification_report(Y_test_binary, y_pred,digits = 4))


svc = SVC()
svm_train()

[[31468  2745]
 [10699 11824]]
              precision    recall  f1-score   support

           0     0.7463    0.9198    0.8240     34213
           1     0.8116    0.5250    0.6375     22523

    accuracy                         0.7630     56736
   macro avg     0.7789    0.7224    0.7308     56736
weighted avg     0.7722    0.7630    0.7500     56736



In [3]:
def svm_test(path_test):
    #load the train-test data
    Test = pd.read_csv(path_test)

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarylize the target
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)
    
    #SVM
    y_pred = svc.predict(X_test)
    print(confusion_matrix(Y_test_binary, y_pred))
    print(classification_report(Y_test_binary, y_pred,digits = 4))

# Cleveland

In [4]:
path_test = '../TrainTestdata/cle_test.csv'
svm_test(path_test)

[[7828  707]
 [2670 2979]]
              precision    recall  f1-score   support

           0     0.7457    0.9172    0.8226      8535
           1     0.8082    0.5273    0.6382      5649

    accuracy                         0.7619     14184
   macro avg     0.7769    0.7223    0.7304     14184
weighted avg     0.7706    0.7619    0.7492     14184



# Virginia

In [5]:
path_test = '../TrainTestdata/vir_test.csv'
svm_test(path_test)

[[7978  669]
 [2602 2935]]
              precision    recall  f1-score   support

           0     0.7541    0.9226    0.8299      8647
           1     0.8144    0.5301    0.6422      5537

    accuracy                         0.7694     14184
   macro avg     0.7842    0.7264    0.7360     14184
weighted avg     0.7776    0.7694    0.7566     14184



# Hungary

In [6]:
path_test = '../TrainTestdata/hun_test.csv'
svm_test(path_test)

[[7861  680]
 [2684 2959]]
              precision    recall  f1-score   support

           0     0.7455    0.9204    0.8237      8541
           1     0.8131    0.5244    0.6376      5643

    accuracy                         0.7628     14184
   macro avg     0.7793    0.7224    0.7307     14184
weighted avg     0.7724    0.7628    0.7497     14184



# Switzerland

In [7]:
path_test = '../TrainTestdata/swi_test.csv'
svm_test(path_test)

[[7801  689]
 [2743 2951]]
              precision    recall  f1-score   support

           0     0.7399    0.9188    0.8197      8490
           1     0.8107    0.5183    0.6323      5694

    accuracy                         0.7580     14184
   macro avg     0.7753    0.7186    0.7260     14184
weighted avg     0.7683    0.7580    0.7445     14184

