In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import preprocessing as sk_preprocessing

In [2]:
def svm(path_train,path_test):
    #load the train-test data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarylize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)
    
    #SVM
    svc = SVC()
    svc.fit(X_train, Y_train_binary.values.ravel())
    y_pred = svc.predict(X_test)
    print(confusion_matrix(Y_test_binary, y_pred))
    print(classification_report(Y_test_binary, y_pred))

# Cleveland

In [3]:
path_train = '../TrainTestdata/cle_train.csv'
path_test = '../TrainTestdata/cle_test.csv'
svm(path_train,path_test)

[[7868  667]
 [2899 2750]]
              precision    recall  f1-score   support

           0       0.73      0.92      0.82      8535
           1       0.80      0.49      0.61      5649

    accuracy                           0.75     14184
   macro avg       0.77      0.70      0.71     14184
weighted avg       0.76      0.75      0.73     14184



# Virginia

In [4]:
path_train = '../TrainTestData/vir_train.csv'
path_test = '../TrainTestData/vir_test.csv'
svm(path_train,path_test)

[[8172  475]
 [3052 2485]]
              precision    recall  f1-score   support

           0       0.73      0.95      0.82      8647
           1       0.84      0.45      0.58      5537

    accuracy                           0.75     14184
   macro avg       0.78      0.70      0.70     14184
weighted avg       0.77      0.75      0.73     14184



# Hungary

In [5]:
path_train = '../TrainTestData/hun_train.csv'
path_test = '../TrainTestData/hun_test.csv'
svm(path_train,path_test)

[[8019  522]
 [3083 2560]]
              precision    recall  f1-score   support

           0       0.72      0.94      0.82      8541
           1       0.83      0.45      0.59      5643

    accuracy                           0.75     14184
   macro avg       0.78      0.70      0.70     14184
weighted avg       0.77      0.75      0.73     14184



# Switzerland

In [6]:
path_train = '../TrainTestData/swi_train.csv'
path_test = '../TrainTestData/swi_test.csv'
svm(path_train,path_test)

[[7921  569]
 [3098 2596]]
              precision    recall  f1-score   support

           0       0.72      0.93      0.81      8490
           1       0.82      0.46      0.59      5694

    accuracy                           0.74     14184
   macro avg       0.77      0.69      0.70     14184
weighted avg       0.76      0.74      0.72     14184



# Combined

In [7]:
path_train = '../TrainTestData/com_train.csv'
path_test = '../TrainTestData/com_test.csv'
svm(path_train,path_test)

[[32171  2042]
 [12300 10223]]
              precision    recall  f1-score   support

           0       0.72      0.94      0.82     34213
           1       0.83      0.45      0.59     22523

    accuracy                           0.75     56736
   macro avg       0.78      0.70      0.70     56736
weighted avg       0.77      0.75      0.73     56736

