In [1]:
import numpy as np
import random
import cv2
import os
from imutils import paths
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
import pandas as pd

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Activation, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import SGD
from tensorflow.keras import backend as K
from sklearn.metrics import confusion_matrix, classification_report

In [13]:
A_X_train = pd.read_csv('Hospitalized Data/partialcon_A_X_train.csv')
A_X_test = pd.read_csv('Hospitalized Data/partialcon_A_X_test.csv')
A_Y_train = pd.read_csv('Hospitalized Data/partialcon_A_Y_train.csv')
A_Y_test = pd.read_csv('Hospitalized Data/partialcon_A_Y_test.csv')

In [14]:
B_X_train = pd.read_csv('Hospitalized Data/partialcon_B_X_train.csv')
B_X_test = pd.read_csv('Hospitalized Data/partialcon_B_X_test.csv')
B_Y_train = pd.read_csv('Hospitalized Data/partialcon_B_Y_train.csv')
B_Y_test = pd.read_csv('Hospitalized Data/partialcon_B_Y_test.csv')

In [15]:
C_X_train = pd.read_csv('Hospitalized Data/partialcon_C_X_train.csv')
C_X_test = pd.read_csv('Hospitalized Data/partialcon_C_X_test.csv')
C_Y_train = pd.read_csv('Hospitalized Data/partialcon_C_Y_train.csv')
C_Y_test = pd.read_csv('Hospitalized Data/partialcon_C_Y_test.csv')

In [16]:
D_X_train = pd.read_csv('Hospitalized Data/partialcon_D_X_train.csv')
D_X_test = pd.read_csv('Hospitalized Data/partialcon_D_X_test.csv')
D_Y_train = pd.read_csv('Hospitalized Data/partialcon_D_Y_train.csv')
D_Y_test = pd.read_csv('Hospitalized Data/partialcon_D_Y_test.csv')

In [20]:
X_test = pd.concat([A_X_test,B_X_test,C_X_test,D_X_test])
y_test = pd.concat([A_Y_test,B_Y_test,C_Y_test,D_Y_test])

X_train = pd.concat([A_X_train,B_X_train,C_X_train,D_X_train])
y_train = pd.concat([A_Y_train,B_Y_train,C_Y_train,D_Y_train])

In [24]:
def create_clients():
    A_zip = list(zip(A_X_train.values,A_Y_train))
    B_zip = list(zip(B_X_train.values,B_Y_train))
    C_zip = list(zip(C_X_train.values,C_Y_train))
    D_zip = list(zip(D_X_train.values,D_Y_train))
    
    shards = [A_zip, B_zip, C_zip,D_zip]
    client_names = ["client_1","client_2","client_3","client_4"]
    dic = {client_names[i] : shards[i] for i in range(len(client_names))}
    return dic


def batch_data(data_shard, bs=32):
    '''Takes in a clients data shard and create a tfds object off it
    args:
        shard: a data, label constituting a client's data shard
        bs:batch size
    return:
        tfds object'''
    #seperate shard into data and labels lists
    data, label = zip(*data_shard)
    dataset = tf.data.Dataset.from_tensor_slices((list(data), list(label)))
    return dataset.shuffle(len(label)).batch(bs)


class CNN:
    @staticmethod
    def build(shape, classes):
        model = Sequential()
        model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(20,1)))
        model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
        model.add(MaxPooling1D(pool_size=2))

        model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
        model.add(MaxPooling1D(pool_size=2))

        model.add(Flatten())
        model.add(Dense(256, activation='relu'))
        model.add(Dense(2, activation='sigmoid'))

        model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model
    

def weight_scalling_factor(clients_trn_data, client_name):
    client_names = list(clients_trn_data.keys())
    #get the bs
    bs = list(clients_trn_data[client_name])[0][0].shape[0]
    #first calculate the total training data points across clinets
    global_count = sum([tf.data.experimental.cardinality(clients_trn_data[client_name]).numpy() for client_name in client_names])*bs
    # get the total number of data points held by a client
    local_count = tf.data.experimental.cardinality(clients_trn_data[client_name]).numpy()*bs
    return local_count/global_count


def scale_model_weights(weight, scalar):
    '''function for scaling a models weights'''
    weight_final = []
    steps = len(weight)
    for i in range(steps):
        weight_final.append(scalar * weight[i])
    return weight_final


def sum_scaled_weights(scaled_weight_list):
    '''Return the sum of the listed scaled weights. The is equivalent to scaled avg of the weights'''
    avg_grad = list()
    #get the average grad accross all client gradients
    for grad_list_tuple in zip(*scaled_weight_list):
        layer_mean = tf.math.reduce_sum(grad_list_tuple, axis=0)
        avg_grad.append(layer_mean)
        
    return avg_grad


def test_model(X_test, Y_test,  model, comm_round):
    cce = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    #logits = model.predict(X_test, batch_size=100)
    logits = model.predict(X_test)
    length = len(y_test)
    Y_test = tf.reshape(Y_test,(length,1))
    loss = cce(Y_test, logits)
    acc = accuracy_score(tf.argmax(logits, axis=1), Y_test)
    print('comm_round: {} | global_acc: {:.3%} | global_loss: {}'.format(comm_round, acc, loss))
    return acc, loss

In [26]:
#create clients
clients = create_clients()

#process and batch the training data for each client
clients_batched = dict()
for (client_name, data) in clients.items():
    clients_batched[client_name] = batch_data(data)
    
#process and batch the test set  
test_batched = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(len(y_test))

comms_round = 100
    
#create optimizer
lr = 0.01 
loss='sparse_categorical_crossentropy'
metrics = ['accuracy']
optimizer = tf.keras.optimizers.legacy.SGD(lr=lr, decay=lr / comms_round, momentum=0.9) 

#initialize global model
smlp_global = CNN()
global_model = smlp_global.build(20, 2)
        
#commence global training loop
for comm_round in range(comms_round):
            
    # get the global model's weights - will serve as the initial weights for all local models
    global_weights = global_model.get_weights()
    
    #initial list to collect local model weights after scalling
    scaled_local_weight_list = list()

    #randomize client data - using keys
    client_names= list(clients_batched.keys())
    random.shuffle(client_names)
    
    #loop through each client and create new local model
    for client in client_names:
        smlp_local = CNN()
        local_model = smlp_local.build(20, 2)
        local_model.compile(loss=loss, 
                      optimizer=optimizer, 
                      metrics=metrics)
        
        #set local model weight to the weight of the global model
        local_model.set_weights(global_weights)
        
        #fit local model with client's data
        local_model.fit(clients_batched[client], epochs=1, verbose=0)
        
        #scale the model weights and add to list
        scaling_factor = weight_scalling_factor(clients_batched, client)
        scaled_weights = scale_model_weights(local_model.get_weights(), scaling_factor)
        scaled_local_weight_list.append(scaled_weights)
        
        #clear session to free memory after each communication round
        K.clear_session()
        
    #to get the average over all the local model, we simply take the sum of the scaled weights
    average_weights = sum_scaled_weights(scaled_local_weight_list)
    
    #update global model 
    global_model.set_weights(average_weights)

    #test global model and print out metrics after each communications round
    for(X_test, Y_test) in test_batched:
        global_acc, global_loss = test_model(X_test, Y_test, global_model, comm_round)
        SGD_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train)).shuffle(len(y_train)).batch(250)
        smlp_SGD = CNN()
        SGD_model = smlp_SGD.build(20, 2) 

        SGD_model.compile(loss=loss, optimizer=optimizer, metrics=metrics)

# fit the SGD training data to model
_ = SGD_model.fit(SGD_dataset, epochs=100, verbose=0)

#test the SGD global model and print out metrics
for(X_test, Y_test) in test_batched:
        SGD_acc, SGD_loss = test_model(X_test, Y_test, SGD_model, 1)

D:\Anaconda\envs\GPU\lib\site-packages\keras\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


UnimplementedError: Graph execution error:

Detected at node 'Cast_1' defined at (most recent call last):
    File "D:\Anaconda\envs\GPU\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "D:\Anaconda\envs\GPU\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "D:\Anaconda\envs\GPU\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
      app.start()
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
      self.io_loop.start()
    File "D:\Anaconda\envs\GPU\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "D:\Anaconda\envs\GPU\lib\asyncio\base_events.py", line 601, in run_forever
      self._run_once()
    File "D:\Anaconda\envs\GPU\lib\asyncio\base_events.py", line 1905, in _run_once
      handle._run()
    File "D:\Anaconda\envs\GPU\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
      res = shell.run_cell(
    File "D:\Anaconda\envs\GPU\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "D:\Anaconda\envs\GPU\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_cell
      result = self._run_cell(
    File "D:\Anaconda\envs\GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3016, in _run_cell
      result = runner(coro)
    File "D:\Anaconda\envs\GPU\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "D:\Anaconda\envs\GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3221, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "D:\Anaconda\envs\GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3400, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "D:\Anaconda\envs\GPU\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\Ethan\AppData\Local\Temp\ipykernel_16296\1578888054.py", line 49, in <module>
      local_model.fit(clients_batched[client], epochs=1, verbose=0)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\engine\training.py", line 1055, in train_step
      return self.compute_metrics(x, y, y_pred, sample_weight)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\engine\training.py", line 1149, in compute_metrics
      self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\engine\compile_utils.py", line 605, in update_state
      metric_obj.update_state(y_t, y_p, sample_weight=mask)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\utils\metrics_utils.py", line 77, in decorated
      update_op = update_state_fn(*args, **kwargs)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\metrics\base_metric.py", line 140, in update_state_fn
      return ag_update_state(*args, **kwargs)
    File "D:\Anaconda\envs\GPU\lib\site-packages\keras\metrics\base_metric.py", line 676, in update_state
      y_true = tf.cast(y_true, self._dtype)
Node: 'Cast_1'
Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_train_function_1222]

In [6]:
Y_predictions = np.argmax(SGD_model.predict(X_test),axis = 1)

In [7]:
cm = confusion_matrix(Y_predictions, Y_test)
cm

array([[ 95,  14],
       [ 28, 140]], dtype=int64)

In [8]:
print(classification_report(Y_test, Y_predictions))

              precision    recall  f1-score   support

           0       0.87      0.77      0.82       123
           1       0.83      0.91      0.87       154

    accuracy                           0.85       277
   macro avg       0.85      0.84      0.84       277
weighted avg       0.85      0.85      0.85       277



# Testing on each dataset

In [9]:
Y_cle = np.argmax(SGD_model.predict(cle_X_test),axis = 1)
cm_cle = confusion_matrix(Y_cle, cle_Y_test_binary)
print(cm_cle)
print(classification_report(Y_cle, cle_Y_test_binary))

[[41  3]
 [10 37]]
              precision    recall  f1-score   support

           0       0.80      0.93      0.86        44
           1       0.93      0.79      0.85        47

    accuracy                           0.86        91
   macro avg       0.86      0.86      0.86        91
weighted avg       0.87      0.86      0.86        91



In [10]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_cle, cle_Y_test_binary)) if a != b]
print(mismatch)

[0, 10, 19, 28, 32, 38, 46, 53, 67, 69, 70, 77, 90]


In [11]:
Y_vir = np.argmax(SGD_model.predict(vir_X_test),axis = 1)
cm_vir = confusion_matrix(Y_vir, vir_Y_test_binary)
print(cm_vir)
print(classification_report(Y_vir, vir_Y_test_binary))

[[ 3  4]
 [10 43]]
              precision    recall  f1-score   support

           0       0.23      0.43      0.30         7
           1       0.91      0.81      0.86        53

    accuracy                           0.77        60
   macro avg       0.57      0.62      0.58        60
weighted avg       0.84      0.77      0.79        60



In [12]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_vir, vir_Y_test_binary)) if a != b]
print(mismatch)

[3, 6, 11, 14, 22, 32, 34, 40, 43, 48, 49, 56, 57, 58]


In [13]:
Y_hun = np.argmax(SGD_model.predict(hun_X_test),axis = 1)
cm_hun = confusion_matrix(Y_hun, hun_Y_test_binary)
print(cm_hun)
print(classification_report(Y_hun, hun_Y_test_binary))

[[50  4]
 [ 7 28]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90        54
           1       0.88      0.80      0.84        35

    accuracy                           0.88        89
   macro avg       0.88      0.86      0.87        89
weighted avg       0.88      0.88      0.88        89



In [14]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_hun, hun_Y_test_binary)) if a != b]
print(mismatch)

[12, 13, 14, 23, 29, 36, 42, 45, 46, 54, 85]


In [15]:
Y_swi = np.argmax(SGD_model.predict(swi_X_test),axis = 1)
cm_swi = confusion_matrix(Y_swi, swi_Y_test_binary)
print(cm_swi)
print(classification_report(Y_swi, swi_Y_test_binary))

[[ 1  3]
 [ 1 32]]
              precision    recall  f1-score   support

           0       0.50      0.25      0.33         4
           1       0.91      0.97      0.94        33

    accuracy                           0.89        37
   macro avg       0.71      0.61      0.64        37
weighted avg       0.87      0.89      0.88        37



In [16]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_swi, swi_Y_test_binary)) if a != b]
print(mismatch)

[1, 6, 20, 27]
