In [14]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, CuDNNLSTM
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf

In [7]:
print('GPU Device:', tf.test.gpu_device_name())

GPU Device: /device:GPU:0


In [ ]:
def RNN_train():
    #load the data
    Train = pd.read_csv('../TrainTestData/com_train.csv')
    Test = pd.read_csv('../TrainTestData/com_test.csv')
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]
    
    
    #train the RNN model
    callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)
    with tf.device('/device:GPU:0'):
        history = model.fit(X_train, Y_train,validation_split = 0.1, epochs=25, batch_size=32,callbacks=[callback])
        
    #save model history
    np.save('../Models/history/baseline_RNN_hist.npy',history.history)
    #history=np.load('my_history.npy',allow_pickle='TRUE').item()
    
    #save model
    model.save('../Models/baseline_CNN.h5')
    #new_model = tf.keras.models.load_model('saved_model/my_model')
    
    #plot train val loss
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'val'], loc='upper left')
    plt.show()
    
    #test the model
    Y_pred = model.predict(X_test).argmax(axis=1)
    cm = confusion_matrix(Y_pred, Y_test)
    print(cm)
    print(classification_report(Y_test, Y_pred,digits=4))

def RNN_test(path_test)
    Test = pd.read_csv(path_test)

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test)
    print(cm)
    print(classification_report(Y_test, Y_pred,digits = 4))

In [15]:
# RNN
model = Sequential()
model.add(CuDNNLSTM(units=64, return_sequences=True, input_shape=(35, 1)))
model.add(CuDNNLSTM(units=32, return_sequences=True))
model.add(CuDNNLSTM(units=16))
model.add(Dense(units=2, activation='sigmoid'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

RNN_train()

Epoch 1/25
4137/4137 [==============================] - 35s 8ms/step - loss: 0.6037 - accuracy: 0.6706
Epoch 2/25
4137/4137 [==============================] - 33s 8ms/step - loss: 0.5258 - accuracy: 0.7402
Epoch 3/25
4137/4137 [==============================] - 32s 8ms/step - loss: 0.5102 - accuracy: 0.7534
Epoch 4/25
4137/4137 [==============================] - 33s 8ms/step - loss: 0.5069 - accuracy: 0.7556
Epoch 5/25
4137/4137 [==============================] - 33s 8ms/step - loss: 0.5053 - accuracy: 0.7566
Epoch 6/25
4137/4137 [==============================] - 32s 8ms/step - loss: 0.5033 - accuracy: 0.7575
Epoch 7/25
4137/4137 [==============================] - 33s 8ms/step - loss: 0.5021 - accuracy: 0.7586
Epoch 8/25
4137/4137 [==============================] - 33s 8ms/step - loss: 0.5012 - accuracy: 0.7584
Epoch 9/25
4137/4137 [==============================] - 33s 8ms/step - loss: 0.5000 - accuracy: 0.7588
Epoch 10/25
4137/4137 [==============================] - 32s 8ms/step - l

KeyboardInterrupt: 

In [17]:
path_test = '../TrainTestData/cle_test.csv'
RNN_test(path_test)

444/444 [==============================] - 2s 3ms/step
[[7570 2402]
 [ 965 3247]]
              precision    recall  f1-score   support

           0       0.76      0.89      0.82      8535
           1       0.77      0.57      0.66      5649

    accuracy                           0.76     14184
   macro avg       0.77      0.73      0.74     14184
weighted avg       0.76      0.76      0.75     14184



In [18]:
path_test = '../TrainTestData/vir_test.csv'
RNN_test(path_test)

444/444 [==============================] - 1s 3ms/step
[[7678 2340]
 [ 969 3197]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.82      8647
           1       0.77      0.58      0.66      5537

    accuracy                           0.77     14184
   macro avg       0.77      0.73      0.74     14184
weighted avg       0.77      0.77      0.76     14184



In [19]:
path_test = '../TrainTestData/hun_test.csv'
RNN_test(path_test)

444/444 [==============================] - 1s 3ms/step
[[7593 2403]
 [ 948 3240]]
              precision    recall  f1-score   support

           0       0.76      0.89      0.82      8541
           1       0.77      0.57      0.66      5643

    accuracy                           0.76     14184
   macro avg       0.77      0.73      0.74     14184
weighted avg       0.77      0.76      0.76     14184



In [20]:
path_test = '../TrainTestData/swi_test.csv'
RNN_test(path_test)

444/444 [==============================] - 1s 3ms/step
[[7542 2443]
 [ 948 3251]]
              precision    recall  f1-score   support

           0       0.76      0.89      0.82      8490
           1       0.77      0.57      0.66      5694

    accuracy                           0.76     14184
   macro avg       0.76      0.73      0.74     14184
weighted avg       0.76      0.76      0.75     14184

