In [13]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

In [22]:
def bc_train():
    Train = pd.read_csv('../TrainTestData/com_train.csv')
    Test = pd.read_csv('../TrainTestData/com_test.csv')
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #Bayesian Classifier
    classifier.fit(X_train, Y_train)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test)
    print(cm)
    print(classification_report(Y_test, Y_pred,digits = 4))

classifier = GaussianNB()
bc_train()

[[33060 13886]
 [ 1153  8637]]
              precision    recall  f1-score   support

           0     0.7042    0.9663    0.8147     34213
           1     0.8822    0.3835    0.5346     22523

    accuracy                         0.7349     56736
   macro avg     0.7932    0.6749    0.6746     56736
weighted avg     0.7749    0.7349    0.7035     56736



In [23]:
def bc_test(path_test):
    Test = pd.read_csv(path_test)

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred,digits = 4))

# Cleveland

In [24]:
path_test = '../TrainTestData/cle_test.csv'
bc_test(path_test)

[[8237 3472]
 [ 298 2177]]
              precision    recall  f1-score   support

           0     0.7035    0.9651    0.8138      8535
           1     0.8796    0.3854    0.5359      5649

    accuracy                         0.7342     14184
   macro avg     0.7915    0.6752    0.6749     14184
weighted avg     0.7736    0.7342    0.7031     14184



# Virginia

In [25]:
path_train = '../TrainTestData/vir_train.csv'
path_test = '../TrainTestData/vir_test.csv'
BayesianClassifier(path_train,path_test)

[[8362 3408]
 [ 285 2129]]
              precision    recall  f1-score   support

           0     0.7105    0.9670    0.8191      8647
           1     0.8819    0.3845    0.5355      5537

    accuracy                         0.7396     14184
   macro avg     0.7962    0.6758    0.6773     14184
weighted avg     0.7774    0.7396    0.7084     14184



# Hungary

In [26]:
path_train = '../TrainTestData/hun_train.csv'
path_test = '../TrainTestData/hun_test.csv'
BayesianClassifier(path_train,path_test)

[[8272 3526]
 [ 269 2117]]
              precision    recall  f1-score   support

           0     0.7011    0.9685    0.8134      8541
           1     0.8873    0.3752    0.5273      5643

    accuracy                         0.7324     14184
   macro avg     0.7942    0.6718    0.6704     14184
weighted avg     0.7752    0.7324    0.6996     14184



# Switzerland

In [27]:
path_train = '../TrainTestData/swi_train.csv'
path_test = '../TrainTestData/swi_test.csv'
BayesianClassifier(path_train,path_test)

[[5812 1639]
 [2678 4055]]
              precision    recall  f1-score   support

           0     0.7800    0.6846    0.7292      8490
           1     0.6023    0.7122    0.6526      5694

    accuracy                         0.6956     14184
   macro avg     0.6911    0.6984    0.6909     14184
weighted avg     0.7087    0.6956    0.6984     14184

