In [17]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [18]:
def rf_train():
    Train = pd.read_csv('../TrainTestData/com_train.csv')
    Test = pd.read_csv('../TrainTestData/com_test.csv')
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits = 4))

classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_train()

[[27944  9234]
 [ 6269 13289]]
              precision    recall  f1-score   support

           0     0.7516    0.8168    0.7828     34213
           1     0.6795    0.5900    0.6316     22523

    accuracy                         0.7268     56736
   macro avg     0.7155    0.7034    0.7072     56736
weighted avg     0.7230    0.7268    0.7228     56736



In [19]:
def rf_test(path_test):
    Test = pd.read_csv(path_test)

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits = 4))

# Cleveland

In [20]:
path_test = '../TrainTestData/cle_test.csv'
rf_test(path_test)

[[7004 2336]
 [1531 3313]]
              precision    recall  f1-score   support

           0     0.7499    0.8206    0.7837      8535
           1     0.6839    0.5865    0.6315      5649

    accuracy                         0.7274     14184
   macro avg     0.7169    0.7035    0.7076     14184
weighted avg     0.7236    0.7274    0.7231     14184



# Virginia

In [21]:
path_test = '../TrainTestData/vir_test.csv'
rf_test(path_test)

[[7083 2229]
 [1564 3308]]
              precision    recall  f1-score   support

           0     0.7606    0.8191    0.7888      8647
           1     0.6790    0.5974    0.6356      5537

    accuracy                         0.7326     14184
   macro avg     0.7198    0.7083    0.7122     14184
weighted avg     0.7288    0.7326    0.7290     14184



# Hungary

In [22]:
path_test = '../TrainTestData/hun_test.csv'
rf_test(path_test)

[[6980 2303]
 [1561 3340]]
              precision    recall  f1-score   support

           0     0.7519    0.8172    0.7832      8541
           1     0.6815    0.5919    0.6335      5643

    accuracy                         0.7276     14184
   macro avg     0.7167    0.7046    0.7084     14184
weighted avg     0.7239    0.7276    0.7237     14184



# Switzerland

In [14]:
path_test = '../TrainTestData/swi_test.csv'
rf_test(path_test)

[[6808 2343]
 [1682 3351]]
              precision    recall  f1-score   support

           0     0.7440    0.8019    0.7718      8490
           1     0.6658    0.5885    0.6248      5694

    accuracy                         0.7162     14184
   macro avg     0.7049    0.6952    0.6983     14184
weighted avg     0.7126    0.7162    0.7128     14184

