In [1]:
import numpy as np
import random
import cv2
import os
from imutils import paths
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
import pandas as pd

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Activation, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import SGD
from tensorflow.keras import backend as K
from sklearn.metrics import confusion_matrix, classification_report

In [9]:
#binarize the labels
lb = LabelBinarizer()

import pandas as pd

data_files = ['cle_train.csv','cle_test.csv','hun_train.csv','hun_test.csv','swi_train.csv','swi_test.csv','vir_train.csv','vir_test.csv']

datasets = {}

for file in data_files:
    data = pd.read_csv('TrainTestData/' + file)
    
    X = data.iloc[:, :-1]
    Y = data.iloc[:, -1]
    
    Y_binary = Y.apply(lambda x: 1 if x > 0 else 0)
    
    # Extract the name from the file path
    name = file.split('.')[0]
    
    # Store the dataset components in a dictionary
    datasets[name] = {'X': X, 'Y': Y, 'Y_binary': Y_binary}

# Unpack the dictionary values in a loop
variables = ['cle', 'hun', 'swi', 'vir']
train_test = ['train', 'test']

for var in variables:
    for tt in train_test:
        X, Y, Y_binary = datasets[f'{var}_{tt}'].values()
        globals()[f'{var}_X_{tt}'] = X
        globals()[f'{var}_Y_{tt}'] = Y
        globals()[f'{var}_Y_{tt}_binary'] = Y_binary

In [10]:
X_test = pd.concat([cle_X_test,hun_X_test,swi_X_test,vir_X_test])
y_test = pd.concat([cle_Y_test_binary,hun_Y_test_binary,swi_Y_test_binary,vir_Y_test_binary])

X_train = pd.concat([cle_X_train,hun_X_train,swi_X_train,vir_X_train])
y_train = pd.concat([cle_Y_train_binary,hun_Y_train_binary,swi_Y_train_binary,vir_Y_train_binary])

In [14]:
def create_clients():
    cle_zip = list(zip(cle_X_train.values,cle_Y_train_binary))
    hun_zip = list(zip(hun_X_train.values,hun_Y_train_binary))
    vir_zip = list(zip(vir_X_train.values,vir_Y_train_binary))
    swi_zip = list(zip(swi_X_train.values,swi_Y_train_binary))
    
    shards = [cle_zip, hun_zip, vir_zip,swi_zip]
    client_names = ["client_1","client_2","client_3","client_4"]
    dic = {client_names[i] : shards[i] for i in range(len(client_names))}
    return dic


def batch_data(data_shard, bs=32):
    '''Takes in a clients data shard and create a tfds object off it
    args:
        shard: a data, label constituting a client's data shard
        bs:batch size
    return:
        tfds object'''
    #seperate shard into data and labels lists
    data, label = zip(*data_shard)
    dataset = tf.data.Dataset.from_tensor_slices((list(data), list(label)))
    return dataset.shuffle(len(label)).batch(bs)


class CNN:
    @staticmethod
    def build(shape, classes):
        model = Sequential()
        model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(20,1)))
        model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
        model.add(MaxPooling1D(pool_size=2))

        model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
        model.add(MaxPooling1D(pool_size=2))

        model.add(Flatten())
        model.add(Dense(256, activation='relu'))
        model.add(Dense(2, activation='sigmoid'))

        model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model
    

def weight_scalling_factor(clients_trn_data, client_name):
    client_names = list(clients_trn_data.keys())
    #get the bs
    bs = list(clients_trn_data[client_name])[0][0].shape[0]
    #first calculate the total training data points across clinets
    global_count = sum([tf.data.experimental.cardinality(clients_trn_data[client_name]).numpy() for client_name in client_names])*bs
    # get the total number of data points held by a client
    local_count = tf.data.experimental.cardinality(clients_trn_data[client_name]).numpy()*bs
    return local_count/global_count


def scale_model_weights(weight, scalar):
    '''function for scaling a models weights'''
    weight_final = []
    steps = len(weight)
    for i in range(steps):
        weight_final.append(scalar * weight[i])
    return weight_final


def sum_scaled_weights(scaled_weight_list):
    '''Return the sum of the listed scaled weights. The is equivalent to scaled avg of the weights'''
    avg_grad = list()
    #get the average grad accross all client gradients
    for grad_list_tuple in zip(*scaled_weight_list):
        layer_mean = tf.math.reduce_sum(grad_list_tuple, axis=0)
        avg_grad.append(layer_mean)
        
    return avg_grad


def test_model(X_test, Y_test,  model, comm_round):
    cce = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    #logits = model.predict(X_test, batch_size=100)
    logits = model.predict(X_test)
    length = len(y_test)
    Y_test = tf.reshape(Y_test,(length,1))
    loss = cce(Y_test, logits)
    acc = accuracy_score(tf.argmax(logits, axis=1), Y_test)
    print('comm_round: {} | global_acc: {:.3%} | global_loss: {}'.format(comm_round, acc, loss))
    return acc, loss

In [27]:
#create clients
clients = create_clients()

#process and batch the training data for each client
clients_batched = dict()
for (client_name, data) in clients.items():
    clients_batched[client_name] = batch_data(data)
    
#process and batch the test set  
test_batched = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(len(y_test))

comms_round = 100
    
#create optimizer
lr = 0.01 
loss='sparse_categorical_crossentropy'
metrics = ['accuracy']
optimizer = tf.keras.optimizers.legacy.SGD(lr=lr, decay=lr / comms_round, momentum=0.9) 

#initialize global model
smlp_global = CNN()
global_model = smlp_global.build(20, 2)
        
#commence global training loop
for comm_round in range(comms_round):
            
    # get the global model's weights - will serve as the initial weights for all local models
    global_weights = global_model.get_weights()
    
    #initial list to collect local model weights after scalling
    scaled_local_weight_list = list()

    #randomize client data - using keys
    client_names= list(clients_batched.keys())
    random.shuffle(client_names)
    
    #loop through each client and create new local model
    for client in client_names:
        smlp_local = CNN()
        local_model = smlp_local.build(20, 2)
        local_model.compile(loss=loss, 
                      optimizer=optimizer, 
                      metrics=metrics)
        
        #set local model weight to the weight of the global model
        local_model.set_weights(global_weights)
        
        #fit local model with client's data
        local_model.fit(clients_batched[client], epochs=1, verbose=0)
        
        #scale the model weights and add to list
        scaling_factor = weight_scalling_factor(clients_batched, client)
        scaled_weights = scale_model_weights(local_model.get_weights(), scaling_factor)
        scaled_local_weight_list.append(scaled_weights)
        
        #clear session to free memory after each communication round
        K.clear_session()
        
    #to get the average over all the local model, we simply take the sum of the scaled weights
    average_weights = sum_scaled_weights(scaled_local_weight_list)
    
    #update global model 
    global_model.set_weights(average_weights)

    #test global model and print out metrics after each communications round
    for(X_test, Y_test) in test_batched:
        global_acc, global_loss = test_model(X_test, Y_test, global_model, comm_round)
        SGD_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train)).shuffle(len(y_train)).batch(250)
        smlp_SGD = CNN()
        SGD_model = smlp_SGD.build(20, 2) 

        SGD_model.compile(loss=loss, optimizer=optimizer, metrics=metrics)

# fit the SGD training data to model
_ = SGD_model.fit(SGD_dataset, epochs=100, verbose=0)

#test the SGD global model and print out metrics
for(X_test, Y_test) in test_batched:
        SGD_acc, SGD_loss = test_model(X_test, Y_test, SGD_model, 1)

D:\Anaconda\envs\GPU\lib\site-packages\keras\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


1773/1773 [==============================] - 2s 1ms/step
comm_round: 0 | global_acc: 60.302% | global_loss: 0.6685662269592285
1773/1773 [==============================] - 2s 1ms/step
comm_round: 1 | global_acc: 73.010% | global_loss: 0.6253419518470764
1773/1773 [==============================] - 2s 1ms/step
comm_round: 2 | global_acc: 74.593% | global_loss: 0.6112122535705566
1773/1773 [==============================] - 2s 1ms/step
comm_round: 3 | global_acc: 74.945% | global_loss: 0.606839120388031
1773/1773 [==============================] - 2s 1ms/step
comm_round: 4 | global_acc: 74.150% | global_loss: 0.6079518795013428
1773/1773 [==============================] - 2s 1ms/step
comm_round: 5 | global_acc: 75.437% | global_loss: 0.6099951863288879
1773/1773 [==============================] - 2s 1ms/step
comm_round: 6 | global_acc: 75.488% | global_loss: 0.6116540431976318
1773/1773 [==============================] - 2s 1ms/step
comm_round: 7 | global_acc: 75.354% | global_loss: 0.60

1773/1773 [==============================] - 2s 1ms/step
comm_round: 64 | global_acc: 75.994% | global_loss: 0.6071088910102844
1773/1773 [==============================] - 2s 1ms/step
comm_round: 65 | global_acc: 75.957% | global_loss: 0.6060611605644226
1773/1773 [==============================] - 2s 1ms/step
comm_round: 66 | global_acc: 75.945% | global_loss: 0.604714572429657
1773/1773 [==============================] - 2s 1ms/step
comm_round: 67 | global_acc: 75.984% | global_loss: 0.6053755283355713
1773/1773 [==============================] - 2s 1ms/step
comm_round: 68 | global_acc: 75.931% | global_loss: 0.6042124629020691
1773/1773 [==============================] - 2s 1ms/step
comm_round: 69 | global_acc: 75.932% | global_loss: 0.6033385396003723
1773/1773 [==============================] - 2s 1ms/step
comm_round: 70 | global_acc: 75.941% | global_loss: 0.6044416427612305
1773/1773 [==============================] - 2s 1ms/step
comm_round: 71 | global_acc: 75.992% | global_lo

KeyboardInterrupt: 

In [28]:
Y_predictions = np.argmax(SGD_model.predict(X_test),axis = 1)

1773/1773 [==============================] - 2s 1ms/step


In [29]:
cm = confusion_matrix(Y_predictions, Y_test)
cm

array([[25832,  6824],
       [ 8381, 15699]], dtype=int64)

In [30]:
print(classification_report(Y_test, Y_predictions, digits=4))

              precision    recall  f1-score   support

           0     0.7910    0.7550    0.7726     34213
           1     0.6520    0.6970    0.6737     22523

    accuracy                         0.7320     56736
   macro avg     0.7215    0.7260    0.7232     56736
weighted avg     0.7358    0.7320    0.7334     56736



# Testing on each dataset

In [31]:
Y_cle = np.argmax(SGD_model.predict(cle_X_test),axis = 1)
cm_cle = confusion_matrix(Y_cle, cle_Y_test_binary)
print(cm_cle)
print(classification_report(Y_cle, cle_Y_test_binary, digits=4))

444/444 [==============================] - 1s 1ms/step
[[6474 1727]
 [2061 3922]]
              precision    recall  f1-score   support

           0     0.7585    0.7894    0.7737      8201
           1     0.6943    0.6555    0.6743      5983

    accuracy                         0.7329     14184
   macro avg     0.7264    0.7225    0.7240     14184
weighted avg     0.7314    0.7329    0.7318     14184



In [11]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_cle, cle_Y_test_binary)) if a != b]
print(mismatch)

[0, 10, 19, 22, 28, 32, 38, 43, 46, 53, 67, 68, 69, 70, 77, 90]


In [32]:
Y_vir = np.argmax(SGD_model.predict(vir_X_test),axis = 1)
cm_vir = confusion_matrix(Y_vir, vir_Y_test_binary)
print(cm_vir)
print(classification_report(Y_vir, vir_Y_test_binary, digits=4))

444/444 [==============================] - 1s 1ms/step
[[6597 1674]
 [2050 3863]]
              precision    recall  f1-score   support

           0     0.7629    0.7976    0.7799      8271
           1     0.6977    0.6533    0.6748      5913

    accuracy                         0.7375     14184
   macro avg     0.7303    0.7255    0.7273     14184
weighted avg     0.7357    0.7375    0.7361     14184



In [13]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_vir, vir_Y_test_binary)) if a != b]
print(mismatch)

[3, 6, 11, 14, 22, 32, 34, 40, 48, 49, 56, 58]


In [33]:
Y_hun = np.argmax(SGD_model.predict(hun_X_test),axis = 1)
cm_hun = confusion_matrix(Y_hun, hun_Y_test_binary)
print(cm_hun)
print(classification_report(Y_hun, hun_Y_test_binary, digits=4))

444/444 [==============================] - 1s 1ms/step
[[6414 1692]
 [2127 3951]]
              precision    recall  f1-score   support

           0     0.7510    0.7913    0.7706      8106
           1     0.7002    0.6500    0.6742      6078

    accuracy                         0.7308     14184
   macro avg     0.7256    0.7207    0.7224     14184
weighted avg     0.7292    0.7308    0.7293     14184



In [15]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_hun, hun_Y_test_binary)) if a != b]
print(mismatch)

[12, 13, 14, 23, 29, 36, 42, 45, 46, 54]


In [34]:
Y_swi = np.argmax(SGD_model.predict(swi_X_test),axis = 1)
cm_swi = confusion_matrix(Y_swi, swi_Y_test_binary)
print(cm_swi)
print(classification_report(Y_swi, swi_Y_test_binary, digits=4))

444/444 [==============================] - 1s 1ms/step
[[6347 1731]
 [2143 3963]]
              precision    recall  f1-score   support

           0     0.7476    0.7857    0.7662      8078
           1     0.6960    0.6490    0.6717      6106

    accuracy                         0.7269     14184
   macro avg     0.7218    0.7174    0.7189     14184
weighted avg     0.7254    0.7269    0.7255     14184



In [17]:
mismatch = [i for i, (a,b) in enumerate(zip(Y_swi, swi_Y_test_binary)) if a != b]
print(mismatch)

[1, 6, 20, 27]
